name: Swift

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj

    - name: Cache RubyGems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: ${{ runner.os }}-gem-

    - name: Bundle Install
      run: bundle install

    - name: Build and Test
      run: bundle exec fastlane tests